### ISSUE TITLE
What license you use?

### ISSUE THREAD

**Issue by yuriilychak** [chartinger/krita-unofficial-spine-export#1]
Hello @chartinger. I add [topic](http://esotericsoftware.com/forum/Krita-export-plugin-10507) in spine runtimes, to create official Krita export plugin, and developers of Spine want to know can they use your script as base for official.

**Comment by chartinger** [comment]
Yes of course. Would the MIT licence be ok for that?

**Comment by chartinger** [comment]
Closing (now under spine CLA)
