### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by TheGambleri** [chartinger/krita-unofficial-spine-export#2]
Running the script causes following error to appear:

> Traceback (most recent call last):
>   File "...\krita\pykrita\unofficialspineexport\unofficialspineexport.py", line 53, in exportDocument
>     self._export(document.rootNode(), self.directory)
>   File "...\krita\pykrita\unofficialspineexport\unofficialspineexport.py", line 110, in _export
>     child.save(layerFileName, 96, 96)
> TypeError: save(self, str, float, float, InfoObject, QRect = QRect()): not enough arguments

![Capture](https://user-images.githubusercontent.com/53058598/61484102-d386c180-a9a6-11e9-9e4d-44d660c292ce.PNG)

Krita version: 4.2.0

**Comment by chartinger** [comment]
Seems like the API has changed on the way to 4.2.3. Should be fixed with 08418876da3b8ba21995f35cd832d86b10016513.
Tested with Krita 4.2.3 and Spine 3.8.52-beta.

**Comment by TheGambleri** [comment]
That's great! I will test in near future.

**Comment by TheGambleri** [comment]
Now this works perfectly. Big thanks!
